#!/usr/bin/env python3
"""
Automated logo trace pipeline
==============================
Converts the reference PNG to SVG paths for use in ac-logo.ts and favicon.svg.

Usage:
    pip install vtracer pillow
    python3 scripts/trace-logo.py

Output files are written directly to:
    src/components/ac-logo.ts
    public/favicon.svg

Source PNG:
    lars_erik_aa_My_company_has_the_initials_AC_and_I_work_as_an_in_ac1dbb32-059f-49ec-825e-4413495a056c-1.png
"""

import pathlib, re, math, textwrap, tempfile
import vtracer

REPO    = pathlib.Path(__file__).parent.parent
PNG     = REPO / ("lars_erik_aa_My_company_has_the_initials_AC_and_I_work_as_an_in_"
                  "ac1dbb32-059f-49ec-825e-4413495a056c-1.png")
assert PNG.exists(), f"PNG not found: {PNG}"

# ── 1. Trace ──────────────────────────────────────────────────────────────
with tempfile.NamedTemporaryFile(suffix=".svg", delete=False) as tmp:
    traced_svg_path = tmp.name

vtracer.convert_image_to_svg_py(
    str(PNG), traced_svg_path,
    colormode        = "binary",
    filter_speckle   = 4,
    corner_threshold = 60,
    length_threshold = 4.0,
    splice_threshold = 45,
    path_precision   = 3,
)
print(f"[1] vtracer → {traced_svg_path}")

# ── 2. Parse SVG ──────────────────────────────────────────────────────────
raw_svg = pathlib.Path(traced_svg_path).read_text()

path_re = re.compile(
    r'<path\s+d="(?P<d>[^"]+)"\s+fill="(?P<fill>[^"]+)"'
    r'(?:\s+transform="translate\((?P<tx>-?\d+),(?P<ty>-?\d+)\)")?'
)
all_paths = [m.groupdict() for m in path_re.finditer(raw_svg)]

# ── 3. Extract logo body sub-paths (from the compound path) ───────────────
def split_subpaths(d: str) -> list:
    return [p.strip() for p in re.split(r'(?<=Z)\s+(?=M)', d) if p.strip()]

logo_body = split_subpaths(all_paths[0]["d"])[1:]   # skip canvas boundary

# ── 4. Donut hole paths → absolute coordinates ────────────────────────────
arity = {"M":2,"L":2,"T":2,"C":6,"S":4,"Q":4,"A":7,"H":1,"V":1,"Z":0}

def apply_translate(d: str, tx: float, ty: float) -> str:
    tokens = re.findall(r'[A-Za-z]|[-+]?\d*\.?\d+(?:e[-+]?\d+)?', d)
    out, i, cmd = [], 0, None
    while i < len(tokens):
        t = tokens[i]
        if t.isalpha():
            cmd = t.upper(); out.append(t); i += 1
        else:
            n = arity.get(cmd, 0)
            nums = tokens[i:i+n]
            if cmd in ("M","L","T"):
                out += [f"{float(nums[0])+tx:.3f}", f"{float(nums[1])+ty:.3f}"]
            elif cmd == "C":
                out += [f"{float(nums[0])+tx:.3f}", f"{float(nums[1])+ty:.3f}",
                        f"{float(nums[2])+tx:.3f}", f"{float(nums[3])+ty:.3f}",
                        f"{float(nums[4])+tx:.3f}", f"{float(nums[5])+ty:.3f}"]
            elif cmd == "S":
                out += [f"{float(nums[0])+tx:.3f}", f"{float(nums[1])+ty:.3f}",
                        f"{float(nums[2])+tx:.3f}", f"{float(nums[3])+ty:.3f}"]
            elif cmd == "H":
                out.append(f"{float(nums[0])+tx:.3f}")
            elif cmd == "V":
                out.append(f"{float(nums[0])+ty:.3f}")
            else:
                out.extend(nums)
            i += n
    return " ".join(out)

holes = [
    apply_translate(p["d"], float(p["tx"]), float(p["ty"]))
    for p in all_paths[1:]
    if p.get("tx") and not (p["tx"] == "0" and p.get("ty","0") == "0")
]

# ── 5. Combine and compute tight viewBox ─────────────────────────────────
combined_d_raw = " ".join(logo_body + holes)

nums = [float(n) for n in re.findall(r'[-+]?\d*\.?\d+', " ".join(logo_body))]
PAD  = 6
vb_x = math.floor(min(nums[0::2])) - PAD
vb_y = math.floor(min(nums[1::2])) - PAD
vb_w = math.ceil(max(nums[0::2])) - vb_x + PAD
vb_h = math.ceil(max(nums[1::2])) - vb_y + PAD

# Translate to origin
combined_d = apply_translate(combined_d_raw, -vb_x, -vb_y)
viewBox    = f"0 0 {vb_w} {vb_h}"
print(f"[2] viewBox: {viewBox},  sub-paths: {combined_d.count('M')},  chars: {len(combined_d)}")

# ── 6. Write ac-logo.ts ───────────────────────────────────────────────────
SOURCE_PNG = PNG.name
comp = f'''\
import {{ LitElement, html, css }} from 'lit';
import {{ customElement, property }} from 'lit/decorators.js';

/**
 * <ac-logo> – Automated SVG trace of the Aabech Consulting "AC" monogram.
 *
 * Path data generated by vtracer from the reference PNG:
 *   {SOURCE_PNG}
 * Regenerate with: python3 scripts/trace-logo.py
 *
 * CSS custom properties:
 *   --ac-color   fill colour     (default: white)
 *   --ac-size    width & height  (default: 120px)
 *
 * Attributes:
 *   animated   (boolean) – fade-in animation on mount
 */
@customElement('ac-logo')
export class AcLogo extends LitElement {{
  @property({{ type: Boolean, reflect: true }}) animated = false;

  static styles = css`
    :host {{
      display: inline-block;
      width:  var(--ac-size, 120px);
      height: var(--ac-size, 120px);
    }}

    svg {{
      width: 100%;
      height: 100%;
    }}

    .ac-mark {{
      fill: var(--ac-color, white);
      fill-rule: evenodd;
    }}

    /* fade-in animation (only when [animated]) */
    :host([animated]) .ac-mark {{
      opacity: 0;
      animation: ac-appear 0.6s ease-out forwards 0.05s;
    }}

    @keyframes ac-appear {{
      to {{ opacity: 1; }}
    }}
  `;

  render() {{
    return html`
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox="{viewBox}"
        role="img"
        aria-label="AC – Aabech Consulting"
      >
        <title>AC – Aabech Consulting</title>
        <path class="ac-mark" d="{combined_d}"/>
      </svg>
    `;
  }}
}}
'''
(REPO / "src/components/ac-logo.ts").write_text(comp)
print(f"[3] Written src/components/ac-logo.ts")

# ── 7. Write favicon.svg ─────────────────────────────────────────────────
favicon = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewBox}">\n  <path fill-rule="evenodd" fill="white" d="{combined_d}"/>\n</svg>\n'
(REPO / "public/favicon.svg").write_text(favicon)
print(f"[4] Written public/favicon.svg")
print("Done.")
